[package]
name = "rust-solution"
version = "0.1.0"
authors = ["YangKian <45479280+YangKian@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
